### ISSUE TITLE
deprecate capital cased package

### ISSUE THREAD

**Issue by Guria** [vjeux/URLON#7]
npm [requires](https://docs.npmjs.com/getting-started/using-a-package.json#requirements) package name to be all lower cased.
I will deprecate capital cased one.

**Comment by vjeux** [comment]
Sgtm. I was a noob at npm at the time

**Comment by Guria** [comment]
Hmm. Deprecate doesn't work on my side. Maybe it must run only owner. Could you try to run: 
`https://registry.npmjs.org/URLON`

**Comment by vjeux** [comment]
Doesn't seem to work...

"ERR! "URLON status = 403" : URLON"

**Comment by Guria** [comment]
Just got email from npm team. The have deprecated capiral cased package for us.

**Comment by vjeux** [comment]
Thanks!
